name: adnerf
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - autopep8=1.5.7=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.5.25=h06a4308_1
  - cairo=1.14.12=h8948797_3
  - certifi=2021.5.30=py37h06a4308_0
  - configargparse=1.4=pyhd3eb1b0_0
  - cudatoolkit=11.1.1=h6406543_8
  - cycler=0.10.0=py37_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.1=h6c09931_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.63.1=h5a9c865_0
  - graphite2=1.3.14=h23475e2_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=he6710b0_3
  - imageio=2.9.0=pyhd3eb1b0_0
  - intel-openmp=2021.2.0=h06a4308_610
  - jasper=2.0.14=h07fcdf6_1
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py37h2531618_0
  - lcms2=2.12=h3be6417_0
  - libedit=3.1.20210216=h27cfd23_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglu=9.0.0=hf484d3e_1
  - libgomp=9.3.0=h5101ec6_17
  - libllvm10=10.0.1=hbcb73fb_5
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.41.0=h7f98852_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - llvmlite=0.36.0=py37h612dafd_4
  - lz4-c=1.9.3=h2531618_0
  - matplotlib=3.3.4=py37h06a4308_0
  - matplotlib-base=3.3.4=py37h62a2d02_0
  - mkl=2021.2.0=h06a4308_296
  - mkl-service=2.3.0=py37h27cfd23_1
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.1=py37ha9443f7_2
  - natsort=7.1.1=pyhd3eb1b0_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=h4bd325d_0
  - numba=0.53.1=py37ha9443f7_0
  - numpy=1.20.2=py37h2d18471_0
  - numpy-base=1.20.2=py37hfae3a4d_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1k=h27cfd23_0
  - pandas=1.2.4=py37h2531618_0
  - pcre=8.44=he6710b0_0
  - pillow=8.2.0=py37he98fc37_0
  - pip=21.1.2=py37h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.1=h0371630_7
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.8.1=py3.7_cuda11.1_cudnn8.0.5_0
  - pytz=2021.1=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - resampy=0.2.2=py_0
  - scikit-learn=0.24.2=py37ha9443f7_0
  - scipy=1.6.2=py37had2a1c9_1
  - setuptools=52.0.0=py37h06a4308_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.33.0=h62c20be_0
  - tbb=2020.3=hfd86e86_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.8.1=py37
  - torchvision=0.2.2=py_3
  - tornado=6.1=py37h27cfd23_0
  - tqdm=4.59.0=pyhd3eb1b0_1
  - typing_extensions=3.10.0.0=pyha770c72_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.13.0
    - astor==0.8.1
    - cached-property==1.5.2
    - chardet==4.0.0
    - decorator==4.4.2
    - face-alignment==1.3.4
    - fvcore==0.1.5.post20210617
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.38.0
    - h5py==3.2.1
    - idna==2.10
    - importlib-metadata==4.5.0
    - iopath==0.1.8
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - networkx==2.5.1
    - opencv-python==4.5.2.54
    - opt-einsum==3.3.0
    - portalocker==2.3.0
    - protobuf==3.17.3
    - python-speech-features==0.6
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - requests==2.25.1
    - scikit-image==0.18.1
    - tabulate==0.8.9
    - tensorboard==1.15.0
    - tensorflow-estimator==1.15.1
    - tensorflow-gpu==1.15.2
    - termcolor==1.1.0
    - tifffile==2021.6.14
    - urllib3==1.26.5
    - werkzeug==2.0.1
    - wrapt==1.12.1
    - yacs==0.1.8
    - zipp==3.4.1
